- name: Lee's Test Playbook for Skytap
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/skytap.yml

  tasks:
    - set_fact:
        env_name: dev1
        
    - import_tasks: tasks/get_envy_by_tag.yml
